CREATE TABLE `Employees` (
	`EmployeeId`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`DepartmentId`	INTEGER NOT NULL,
	`FirstName`	TEXT NOT NULL,
	`LastName`	TEXT NOT NULL,
	`Supervisor`	TEXT NOT NULL
);
CREATE TABLE `TrainingPrograms` (
`TrainingProgramId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
`StartDate` INTEGER NOT NULL,
`EndDate` INTEGER NOT NULL,
`MaximumAttendees`  INTEGER NOT NULL
);
CREATE TABLE `Departments` (
`DepartmentId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
`ExpenseBudget` INTEGER NOT null
);
CREATE TABLE `Computers` (
	`ComputerId`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`PurchaseDate`	INTEGER NOT NULL,
	`DecommissionDate`	INTEGER,
	`AssignmentStartDate`	INTEGER,
	`AssignmentEndDate`	INTEGER
);
CREATE TABLE `EmpTrainingPrograms` (
	`EmpTrainingProgramId`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`EmployeeId`	INTEGER NOT NULL,
	`TrainingProgramId`	INTEGER NOT NULL
);
CREATE TABLE `EmployeeComputers` (
	`EmpComputerId`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`EmployeeId`	INTEGER NOT NULL,
	`ComputerId`	INTEGER NOT NULL
);
CREATE TABLE `Products` (
`ProductId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
`CustomerId` INTEGER NOT NULL ,
`Title` TEXT NOT NULL,
`Price` DOUBLE NOT NULL,
`Description` TEXT NOT NULL,
`Qty` INTEGER NOT null
);
CREATE TABLE `PaymentTypes` (
`PaymentTypeId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
`CustomerId` INTEGER NOT NULL,
`PaymentName` TEXT NOT NULL,
`AccountNumber` INTEGER NOT NULL 
);
CREATE TABLE `Customers` (
`CustomerId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
`FirstName` TEXT NOT NUll,
`LastName` TEXT NOT NULL,
`RegistrationDate` INTEGER NOT NULL,
`LastLoginDate` INTEGER NOT NULL 
);
CREATE TABLE `ProductOrder` (
`ProductOrderId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
`ProductId` INTEGER NOT NULL,
`OrderId` INTEGER NOT null
);
CREATE TABLE `Orders` (
`OrderId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
`CustomerId` INTEGER NOT NULL,
`PaymentTypeId` INTEGER NOT NULL
);
CREATE TABLE `Product Types` (
`ProductTypeId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
`Name` STRING NOT NULL
);
CREATE TABLE `Computers` (
`ComputerId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
`PurchaseDate` STRING NOT NULL,
`DecommissionDate` STRING,
`AssignmentStartDate` STRING,
`AssignmentEndDate` STRING
);


`